# Generated by Django 3.0.2 on 2020-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
