# Generated by Django 3.0.2 on 2020-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicband',
            name='musical_style',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
