# Generated by Django 3.0.2 on 2020-01-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0002_auto_20200121_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='hw22.Track'),
        ),
    ]
