# Generated by Django 3.0.2 on 2020-01-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw22', '0004_auto_20200121_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='which_albums',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='hw22.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
